# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Session-Driver-memcached
version:      0.03
version_from: lib/CGI/Session/Driver/memcached.pm
installdirs:  site
requires:
    CGI::Session:                  4
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
